import {UserProvider} from "@/contexts/UserContext";
import Head from "next/head";

export const metadata = {
  title: "myresto",
  description: "Generated by Next.js"
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/myresto.svg" type="image/svg+xml" />
        <meta property="og:image" content="/myresto.svg" />
        <meta name="twitter:image" content="/myresto.svg" />
      </Head>
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
